### ISSUE TITLE
Disable SBAS in receiver

### ISSUE THREAD

**Issue by jepler** [HarrydeBug/1009-GPS_Derived_RF_Generator#4]
In section 12.2 of "u-blox 7 receiver description", ublox states "For best time pulse performance it is recommended to disable the SBAS subsystem", though elsewhere (Section 3) it states "For maximum GPS coldstart sensitivity, ensure that the SBAS subsystem is disabled".

It would be nice, then, to send a UBX-CFG-SBAS packet disabling SBAS after initial position fix.

Sending a UBX-CFG-NAV5 to set the model to "stationary" might also be beneficial.

While these items are mentioned in the ublox manuals, they don't quantify the improvement that might be seen.  I don't imagine it would be measurable on any of my own test equipment.

**Comment by jepler** [comment]
However, setting the platform model to "stationary" might preclude using the module in a moving vehicle, so without any clear evidence of a benefit this setting should probably be left alone.

**Comment by HarrydeBug** [comment]
Agree. And I'm guessing many of these recommendation are only useful to lower the timing jitter on the timing specific receivers like the Neo-6T.
For example I did some experiments with putting the receiver in Survey-In mode but it didn't seem to work and never completed the survey so I'm guessing it's a Neo-6T/Lea6 specific thing.

As the modules fitted are standard Neo6 I would say the best method for improving precision and getting the lowest jitter in the timing signal would be:
1. Have a good view of the sky with the GPS antenna.
2. Pick a frequency output that 48MHz can divide in to with Integer math.
3. Average the signal over some time like 10 to 100 seconds.

**Comment by HarrydeBug** [comment]
Closing without action.
